version: '3.8'

services:
  api-sapceship:
    container_name: api-spaceship
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis-spaceship
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis-spaceship
    networks:
      - app-network

  redis-spaceship:
    container_name: redis-spaceship
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
