spring:
  application:
    name: Space.ship
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379
    timeout: 500ms
    time-to.live: 30000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 200ms
  cache:
    type: redis
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      redisCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        ring-buffer-size-in-half-open-state: 2
        ring-buffer-size-in-closed-state: 10
        minimum-number-of-calls: 10
  retry:
    instances:
      redisCircuitBreaker:
        max-attempts: 1
        wait-duration: 0

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: space-ship-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: space-ship-topic